# Generated by Django 5.0.7 on 2024-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_ad_options_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
