# Generated by Django 5.1 on 2024-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_ad_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='body',
        ),
    ]
